ingress:
  # -- If set to `true`, DAPS will be exposed with ingress controller at http(s)://(ingress.host)/(ingress.pathPrefix)
  enabled: true
  # -- Additional ingress annotations
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: "true"
  # -- Ingress host name
  host: daps.pre-prod.demo.catena-x.net
  # -- Path prefix to be added to DAPS URI. Regex can be used
  pathPrefix: "/"
  # -- Root prefix without regex rules that used to configure daps host name in configuration
  rootPath: "/"
  tls:
    # -- If `true` daps will be exposed with https
    enabled: true

    certMgr:
      # -- If `true` cert-manager will be used to issue a certificate with ingress.host CN name
      enabled: true
      # -- Cert-manager issuer name
      issuer: "letsencrypt-prod"

daps:
  secret:
    clientId: "<path:essential-services/data/daps-preprod#clientId>"
    clientSecret: "<path:essential-services/data/daps-preprod#clientSecret>"
