ingress:
  enabled: true
  host: daps.dev.demo.ftcpro.co
  tls:
    enabled: true
    certMgr:
      enabled: true
      issuer: "letsencrypt-prod"

resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 60Mi

persistence:
  enabled: true
  storageClass: "local-storage"
  storageSize: "1Gi"

omejdn:
  createDefaultAdmin: true

# env:
#   secret:
#   - name: OMEJDN_ADMIN
#     value: "<path:portal/data/dev/daps#adminuser>"

daps:
  secret:
    clientId: "<path:portal/data/dev/daps#clientId>"
    clientSecret: "<path:portal/data/dev/daps#clientSecret>"