apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "omejdn-server.fullname" . }}
  labels:
    {{- include "omejdn-server.labels" . | nindent 4 }}
data:
  {{- if .Values.omejdn.serverKey }}
  key.pem: {{ .Values.omejdn.serverKey | b64enc }}
  {{- end }}
{{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
{{- end}}
